openapi: 3.0.0
info:
  title: WeLocal Freemarket Service API
  description: API для управления объявлениями и товарами на свободном рынке
  version: 1.0.0

servers:
  - url: http://localhost:10410
    description: Локальный сервер разработки

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        category:
          type: string
        sellerId:
          type: string
          format: uuid
        images:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [ACTIVE, SOLD, ARCHIVED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

paths:
  /products:
    get:
      summary: Получение списка товаров
      tags:
        - Товары
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [ACTIVE, SOLD, ARCHIVED]
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Успешное получение списка товаров
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка сервера

    post:
      summary: Создание нового товара
      tags:
        - Товары
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - price
                - category
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                category:
                  type: string
                images:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Товар успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Неверные данные
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка сервера

  /products/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Получение информации о товаре
      tags:
        - Товары
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешное получение информации о товаре
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
        '500':
          description: Внутренняя ошибка сервера

    put:
      summary: Обновление информации о товаре
      tags:
        - Товары
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                category:
                  type: string
                status:
                  type: string
                  enum: [ACTIVE, SOLD, ARCHIVED]
                images:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Товар успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Неверные данные
        '401':
          description: Не авторизован
        '404':
          description: Товар не найден
        '500':
          description: Внутренняя ошибка сервера

    delete:
      summary: Удаление товара
      tags:
        - Товары
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Товар успешно удален
        '401':
          description: Не авторизован
        '404':
          description: Товар не найден
        '500':
          description: Внутренняя ошибка сервера 